### ISSUE TITLE
"luarocks install lyaml" encounter error,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [fcambus/motyl#3]
hi.

root@localhost:/usr/local/motyl-site/examples# luarocks install lyaml
Installing http://luarocks.org/repositories/rocks/lyaml-6.1.1-4.src.rock...
Using http://luarocks.org/repositories/rocks/lyaml-6.1.1-4.src.rock... switching to 'build' mode
Archive:  /tmp/luarocks_luarocks-rock-lyaml-6.1.1-4-2306/lyaml-6.1.1-4.src.rock
  inflating: lyaml-6.1.1-4.rockspec  
 extracting: v6.1.1.zip              

Error: Could not find expected file libyaml.a, or libyaml.so, or libyaml.so.* for YAML -- you may have to install YAML in your system and/or pass YAML_DIR or YAML_LIBDIR to the luarocks command. Example: luarocks install lyaml YAML_DIR=/usr/local
root@localhost:/usr/local/motyl-site/examples# 

tks

**Comment by fcambus** [comment]
It seems you need to install the libyaml dev package on your system before trying to install lyaml from Luarocks.

**Comment by luckypoem** [comment]
hi.
wget http://pyyaml.org/download/libyaml/yaml-0.1.7.tar.gz
tar zxvf yaml-0.1.7.tar.gz
cd yaml-0.1.7
./configure
make
make install

thus libyaml is installed successfully.

root@localhost:/usr/local/motyl-site/examples# ls ../src
motyl.lua
root@localhost:/usr/local/motyl-site/examples# cp ../src/motyl.lua ./
root@localhost:/usr/local/motyl-site/examples# ls
Makefile  motyl.conf  motyl.lua  pages  posts  static
root@localhost:/usr/local/motyl-site/examples# ./motyl.lua
lua: ./motyl.lua:30: themes/templates/header.mustache: No such file or directory
stack traceback:
	[C]: in function 'assert'
	./motyl.lua:30: in function 'readFile'
	./motyl.lua:76: in main chunk
	[C]: ?
root@localhost:/usr/local/motyl-site/examples#

where to clone themes ? can u publish the source code of ur site https://www.cambus.net for me to
clone the themes?
tks a lot.

**Comment by fcambus** [comment]
The theme can be found here: https://github.com/fcambus/chrysalide

It's still a moving target though, and things are likely to change before I tag version 1.00.

**Comment by luckypoem** [comment]
hello.

i setup a blog : http://mt.bright.biz.st/ ,but i cannot insert iframe code?
pls see here: http://mt.bright.biz.st/bilu/

how to fix it?
