### ISSUE TITLE
Error syntax in header.mustache

### ISSUE THREAD

**Issue by easybeau** [fcambus/motyl#8]
Hi,

Thank you for this static site generator.

I'm trying to custom the menu with a new theme. Here the original html menu:

> <div id="menu">
			<ul>
				<li class="current_page_item"><a href="#" accesskey="1" title="">Services</a></li>
				<li><a href="#" accesskey="2" title="">Our Clients</a></li>
				<li><a href="#" accesskey="3" title="">About Us</a></li>
				<li><a href="#" accesskey="4" title="">Careers</a></li>
				<li><a href="#" accesskey="5" title="">Contact Us</a></li>
			</ul>
</div>

In header.mustache, I tried to insert these lines:

![xyz](https://user-images.githubusercontent.com/7128391/87947268-6028fb80-caa3-11ea-8d5a-120f25fb7e77.png)

But I have an error :

> /var/lib/gems/2.7.0/gems/mustache-1.1.1/lib/mustache/parser.rb:286:in `error': Unclosed section "sitepages" (Mustache::Parser::SyntaxError)
  Line 34
    {{#site.pages}}

Which syntax is correct ?

Best wishes

**Comment by easybeau** [comment]
Hi,

I keep looking for the correct syntax. I tried this

![Capture d’écran_2020-07-21_06-29-58](https://user-images.githubusercontent.com/7128391/88013163-031d5c00-cb1c-11ea-98a7-246d5abe5eb8.png)

The result is

![home](https://user-images.githubusercontent.com/7128391/88013181-12040e80-cb1c-11ea-81d7-ed5fb76c4661.png)

**Comment by fcambus** [comment]
Hi,

Did you solve this issue in the end?
